### ISSUE TITLE
species_code and filename should be the CUTECODE

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/SDM_Tools#13]
the species code field should have the CuteCode (first four Genus + first four Species) instead of the GNAME.  Also, the filename should be based on the CuteCode.

**Comment by memoore** [comment]
Done, but not sure what to do with sub-species. This takes the first four from the first 2 words and combines. So, if it's a sub-species this may be confusing. We can re-visit when we need to.

**Comment by ChristopherTracey** [comment]
Seems like a decent approach.
