### ISSUE TITLE
Make aquatic grouping tool work in ArcPro

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/SDM_Tools#2]

**Comment by memoore** [comment]
Not yet.

**Comment by ChristopherTracey** [comment]
We should work on it for some point for MoBI as ArcPro is installed on that machine.

**Comment by memoore** [comment]
The network grouping tool now works in pro. There are now two different versions of the tool (with only 1 line of code that's different) - one for arcmap and one for arcpro. Will update soon after other changes.
