### ISSUE TITLE
Develop protocol for lines/polygons

### ISSUE THREAD

**Issue by memoore** [PNHP/SDM_Tools#3]

**Comment by ChristopherTracey** [comment]
After playing with this a little today, I think our order of operations should be:

1. The user preps three datasets: one each for points, line and, polygon data. This should include a field named 'include' and it should contain y/n values. 
2. Using only the records with include=y, use the '[feature vertices to points](http://pro.arcgis.com/en/pro-app/tool-reference/data-management/feature-vertices-to-points.htm)' ArcGIS tool to convert the line and polygon data to points.  Use the 'all' option for output point features.
3. Merge the line and polygon vertices to the prepped points layer, again with the include=y condition met.

It should be pretty simple. Then we can feed this data into the grouper part of the tool.

**Comment by ChristopherTracey** [comment]
@memoore, I spent some time today and wrote a rough python script `1_NetworkGroupingPrep.py` that does the second and third items on the list above.  Could you take a look and clean it up, as you know how my python usually goes.

**Comment by memoore** [comment]
Incorporated this into one script with the rest of the network grouping tool and everything is running smoothly with incorporating lines and polygons.
